config/routes.rb
Rails.application.routes.draw do
  resources :pos
  root 'pos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/po.rb
class Po < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pos_controller.rb
class PosController < ApplicationController
  before_action :set_po, only: [:show, :edit, :update, :destroy]

  # GET /pos
  # GET /pos.json
  def index
    @pos = Po.all
  end

  # GET /pos/1
  # GET /pos/1.json
  def show
  end

  # GET /pos/new
  def new
    @po = Po.new
  end

  # GET /pos/1/edit
  def edit
  end

  # POST /pos
  # POST /pos.json
  def create
    @po = Po.new(po_params)

    respond_to do |format|
      if @po.save
        format.html { redirect_to @po, notice: 'Po was successfully created.' }
        format.json { render :show, status: :created, location: @po }
      else
        format.html { render :new }
        format.json { render json: @po.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pos/1
  # PATCH/PUT /pos/1.json
  def update
    respond_to do |format|
      if @po.update(po_params)
        format.html { redirect_to @po, notice: 'Po was successfully updated.' }
        format.json { render :show, status: :ok, location: @po }
      else
        format.html { render :edit }
        format.json { render json: @po.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pos/1
  # DELETE /pos/1.json
  def destroy
    @po.destroy
    respond_to do |format|
      format.html { redirect_to pos_url, notice: 'Po was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_po
      @po = Po.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def po_params
      params.require(:po).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pos_helper.rb
module PosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Museaqo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    hol
    <%= yield %>
  </body>
</html>

app/views/pos/_form.html.erb
<%= form_with(model: po, local: true) do |form| %>
  <% if po.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(po.errors.count, "error") %> prohibited this po from being saved:</h2>

      <ul>
      <% po.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pos/edit.html.erb
<h1>Editing Po</h1>

<%= render 'form', po: @po %>

<%= link_to 'Show', @po %> |
<%= link_to 'Back', pos_path %>

app/views/pos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pos</h1>

<table>
  <thead>
    <tr>
      <th>Names</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pos.each do |po| %>
      <tr>
        <td><%= po.name %></td>
        <td><%= po.title %></td>
        <td><%= po.content %></td>
        <td><%= link_to 'Show', po %></td>
        <td><%= link_to 'Edit', edit_po_path(po) %></td>
        <td><%= link_to 'Destroy', po, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Po', new_po_path %>

app/views/pos/new.html.erb
<h1>New Po</h1>

<%= render 'form', po: @po %>

<%= link_to 'Back', pos_path %>

app/views/pos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @po.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @po.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @po.content %>
</p>

<%= link_to 'Edit', edit_po_path(@po) %> |
<%= link_to 'Back', pos_path %>